const allProducts = [
    {
        id: 1,
        title: "Winflo 10",
        path: "https://rukminim2.flixcart.com/image/720/864/xif0q/shoe/m/b/f/-original-imah4zkm7kuxdy5t.jpeg?q=60&crop=false",
        price: "5000",
        brand: "Nike",
        category: "Sneaker",
        gender: "Men",
        rating: 4.5,
    },
    {
        id: 2,
        title: "Ultraboost 22",
        path: "https://assets.adidas.com/images/w_600,f_auto,q_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg",
        price: "8000",
        brand: "Adidas",
        category: "Sports",
        gender: "Women",
        rating: 4.8,
    },
    {
        id: 3,
        title: "Suede Classic",
        path: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374915/01/sv01/fnd/IND/fmt/png/Suede-Classic-XXI-Unisex-Sneakers",
        price: "6000",
        brand: "Puma",
        category: "Sneaker",
        gender: "Unisex",
        rating: 4.2,
    },
    {
        id: 4,
        title: "Power Men's Shoes",
        path: "https://www.batabd.com/cdn/shop/files/2_480f6028-04ab-459b-a3bd-6ed92fabdcb8_300x.jpg?v=1712201129",
        price: "3000",
        brand: "Bata",
        category: "Casual",
        gender: "Men",
        rating: 4.0,
    },
    {
        id: 5,
        title: "NMD_R1 Primeblue",
        path: "https://assets.adidas.com/images/w_600,f_auto,q_auto/c10fcd90c433455e8f79ad0800cb4469_9366/NMD_R1_Shoes_Black_GZ9257_01_standard.jpg",
        price: "9000",
        brand: "Adidas",
        category: "Sports",
        gender: "Unisex",
        rating: 4.9,
    },
    {
        id: 6,
        title: "RS-Z Reinvent",
        path: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shoe/a/u/x/-original-imah4erfzr4kh66h.jpeg?q=90&crop=false",
        price: "7000",
        brand: "Puma",
        category: "Sneaker",
        gender: "Women",
        rating: 4.3,
    },
    {
        id: 7,
        title: "Air Zoom Pegasus 39",
        path: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shoe/4/7/8/-original-imah4acq6f2eaghx.jpeg?q=20&crop=false",
        price: "6500",
        brand: "Nike",
        category: "Sports",
        gender: "Men",
        rating: 4.6,
    },
    {
        id: 8,
        title: "Bata Comfit Sandals",
        path: "https://www.bata.com/dw/image/v2/BCLG_PRD/on/demandware.static/-/Sites-bata-in-master-catalog/default/dw595f4198/images/large/5619278_1.jpeg?sw=800&sh=800",
        price: "2500",
        brand: "Bata",
        category: "Sandals",
        gender: "Women",
        rating: 4.1,
    },
    {
        id: 9,
        title: "Adilette Comfort Slides",
        path: "https://suvidhastores.com/wp-content/uploads/2023/09/Adilette_Comfort_Slides_Blue_GZ5892_01_standard.jpg",
        price: "3000",
        brand: "Adidas",
        category: "FlipFlop",
        gender: "Unisex",
        rating: 4.4,
    },
    {
        id: 10,
        title: "Puma Future Z",
        path: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shoe/b/l/p/-original-imahfqnygugphcf6.jpeg?q=90&crop=false",
        price: "7500",
        brand: "Puma",
        category: "Football",
        gender: "Men",
        rating: 4.7,
    },
    {
        id: 11,
        title: "Winflo 10",
        path: "https://rukminim2.flixcart.com/image/720/864/xif0q/shoe/m/b/f/-original-imah4zkm7kuxdy5t.jpeg?q=60&crop=false",
        price: "5000",
        brand: "Nike",
        category: "Sneaker",
        gender: "Women",
        rating: 4.5,
    },
    {
        id: 12,
        title: "Ultraboost 22",
        path: "https://assets.adidas.com/images/w_600,f_auto,q_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg",
        price: "8000",
        brand: "Adidas",
        category: "Sports",
        gender: "Unisex",
        rating: 4.8,
    },
    {
        id:13,
        title: "Suede Classic",
        path: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374915/01/sv01/fnd/IND/fmt/png/Suede-Classic-XXI-Unisex-Sneakers",
        price: "6000",
        brand: "Puma",
        category: "Sneaker",
        gender: "Men",
        rating: 4.2,
    },
    {
        id: 14,
        title: "Power Men's Shoes",
        path: "https://www.batabd.com/cdn/shop/files/2_480f6028-04ab-459b-a3bd-6ed92fabdcb8_300x.jpg?v=1712201129",
        price: "3000",
        brand: "Bata",
        category: "Casual",
        gender: "Men",
        rating: 4.0,
    },
    {
        id: 15,
        title: "NMD_R1 Primeblue",
        path: "https://assets.adidas.com/images/w_600,f_auto,q_auto/c10fcd90c433455e8f79ad0800cb4469_9366/NMD_R1_Shoes_Black_GZ9257_01_standard.jpg",
        price: "9000",
        brand: "Adidas",
        category: "Sports",
        gender: "Women",
        rating: 4.9,
    },
];

export default allProducts;
