const users = [
    {
        id: 1,
        name: "Virat Kohli",
        phone: 4242423535,
        address: "200-A Maninagar, Ahmedabad, Gujarat",
        email: "virat.kohli@example.com",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
        id: 2,
        name: "Rohit Sharma",
        phone: 9876543210,
        address: "101-B Andheri, Mumbai, Maharashtra",
        email: "rohit.sharma@example.com",
        image: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        id: 3,
        name: "MS Dhoni",
        phone: 8765432109,
        address: "12-C Ranchi, Jharkhand",
        email: "ms.dhoni@example.com",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
        id: 4,
        name: "Hardik Pandya",
        phone: 7654321098,
        address: "202-D Baroda, Gujarat",
        email: "hardik.pandya@example.com",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
        id: 5,
        name: "KL Rahul",
        phone: 6543210987,
        address: "303-E Mangalore, Karnataka",
        email: "kl.rahul@example.com",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
        id: 6,
        name: "Shikhar Dhawan",
        phone: 5432109876,
        address: "404-F Delhi",
        email: "shikhar.dhawan@example.com",
        image: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
        id: 7,
        name: "Jasprit Bumrah",
        phone: 4321098765,
        address: "505-G Ahmedabad, Gujarat",
        email: "jasprit.bumrah@example.com",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
        id: 8,
        name: "Ravindra Jadeja",
        phone: 3210987654,
        address: "606-H Rajkot, Gujarat",
        email: "ravindra.jadeja@example.com",
        image: "https://randomuser.me/api/portraits/men/8.jpg",
    },
    {
        id: 9,
        name: "Rishabh Pant",
        phone: 2109876543,
        address: "707-I Roorkee, Uttarakhand",
        email: "rishabh.pant@example.com",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
        id: 10,
        name: "Suryakumar Yadav",
        phone: 1987654321,
        address: "808-J Mumbai, Maharashtra",
        email: "suryakumar.yadav@example.com",
        image: "https://randomuser.me/api/portraits/men/10.jpg",
    },
    {
        id: 11,
        name: "Mohammed Shami",
        phone: 9098765432,
        address: "909-K Amroha, Uttar Pradesh",
        email: "mohammed.shami@example.com",
        image: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    {
        id: 12,
        name: "Yuzvendra Chahal",
        phone: 8987654321,
        address: "100-A Gurgaon, Haryana",
        email: "yuzvendra.chahal@example.com",
        image: "https://randomuser.me/api/portraits/men/12.jpg",
    },
    {
        id: 13,
        name: "Shreyas Iyer",
        phone: 7898765432,
        address: "111-B Chembur, Mumbai, Maharashtra",
        email: "shreyas.iyer@example.com",
        image: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    {
        id: 14,
        name: "Bhuvneshwar Kumar",
        phone: 6787654321,
        address: "222-C Meerut, Uttar Pradesh",
        email: "bhuvneshwar.kumar@example.com",
        image: "https://randomuser.me/api/portraits/men/14.jpg",
    },
    {
        id: 15,
        name: "Axar Patel",
        phone: 5676543210,
        address: "333-D Nadiad, Gujarat",
        email: "axar.patel@example.com",
        image: "https://randomuser.me/api/portraits/men/15.jpg",
    }
];

export default users;
